version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: '20:00'
  target-branch: "3.x"
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: '20:00'
  target-branch: "3.x"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: '20:00'
  target-branch: "4.x"
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: '20:00'
  target-branch: "4.x"
